### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [klosstep/tc359_project11#1]
This is looking mostly good, except I _would_ like to see a link to the Show page, but _not_ see the the _New Pokemon_ link when not logged in.

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by klosstep** [comment]
Dont understand what you mean by "Show" link.  I mean if you click it takes you to the page.

**Comment by chrisvfritz** [comment]
[This is what I mean](https://github.com/klosstep/tc359_project11/blob/master/app/views/pokemons/index.html.erb#L26) by the "Show" link.

**Comment by klosstep** [comment]
i know what you're referring to but im not understanding what you want me to do with that.  it already is linking to a page that displays the data for the submitted entry.  also i do not remember what my password was, what file can i find that in?

**Comment by chrisvfritz** [comment]
Ah, I see. Right now, you can only see that link when a user is logged in, when it should _always_ be visible, even if a user _isn't_ signed in. Does that make sense?

Your password won't be in a file, but accessible through your database. Unfortunately, we're encrypting all the passwords, so you won't be able to see the password itself. If you want to update your password, you can open the `rails console` and do the same thing you did to create a new user, except you'd use the `update` instead of the `create` command (and you only need to include fields you want to update).

**Comment by klosstep** [comment]
okay i apologize this took so long.  Here it is https://limitless-journey-4602.herokuapp.com/pokemons

**Comment by chrisvfritz** [comment]
:+1: Looks great!
